### ISSUE TITLE
pylyzer 0.0.68 fails to build failure on MacOS Sonoma

### ISSUE THREAD

**Issue by Moisan** [mtshiba/pylyzer#112]
**Describe the bug**
When building `pylyzer` I obtain this error:
```
error[E0005]: refutable pattern in local binding
   --> crates/py2erg/convert.rs:450:13
    |
450 |         let Ok(py_program) = locator.fold(py_program);
    |             ^^^^^^^^^^^^^^ pattern `Err(_)` not covered
    |
    = note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant
    = note: for more information, visit https://doc.rust-lang.org/book/ch18-02-refutability.html
    = note: the matched value is of type `Result<ModModule<SourceRange>, Infallible>`
help: you might want to use `let else` to handle the variant that isn't matched
    |
450 |         let Ok(py_program) = locator.fold(py_program) else { todo!() };
    |                                                       ++++++++++++++++

For more information about this error, try `rustc --explain E0005`.
error: could not compile `py2erg` (lib) due to 1 previous error
```

**Reproducible Code**
```
cargo install --jobs 12 --locked --path=.
```

**Expected behavior**
I expect pylyzer to build without errors.

**Screenshots**

**Environment**
 - OS: MacOS Sonoma
 - Version 14.7

**Additional context**
This was spotted while building `pylyzer` for Homebrew. You can see the full logs of this build [here](https://github.com/Homebrew/homebrew-core/actions/runs/11425337771/job/31786915856?pr=195000).

**Comment by Moisan** [comment]
We can succesfully build pylyzer with rust 1.82.0. The build was previously failing with rust 1.81.0.

**Comment by ethanthoma** [comment]
Yeah, I had the same issue on nix and asked on the discord. They said use the latest toolcahin

**Comment by ethanthoma** [comment]
![image](https://github.com/user-attachments/assets/6c7c5ab3-8c16-4dce-896f-df3c06e62103)
