### ISSUE TITLE
Change the parser to something better

### ISSUE THREAD

**Issue by mtshiba** [mtshiba/pylyzer#12]
Currently, pylyzer uses rustpython-parser to parse Python code. However, this parser does not give detailed location information for each token. We will need to change to a better parser or create our own.

**Comment by youknowone** [comment]
Hi, you can use recent version of `rustpython-parser` with `all-nodes-with-ranges` feature. https://github.com/RustPython/Parser/blob/main/parser/Cargo.toml#L15
If the location information is still not enough, we are open to add new features unless it break CPython compatibility.

I tried to upgrade parser, but 0.1.2 is too old one (many years) to trivially upgrade to the new one.

**Comment by mtshiba** [comment]
The feature looks good. I will give it a try.
