### ISSUE TITLE
Problem with start pylyzer on neovim

### ISSUE THREAD

**Issue by kobzar** [mtshiba/pylyzer#21]
Hi. Help me undestand how to make to pylyzer work for me. 
I am use two prebuilds on neovim
LunarVim
https://www.lunarvim.org/
LazyVim
https://www.lazyvim.org/configuration/general

Both of them use Mason plugins manager.
My OS is VoidLinux and MacOS

I have installed rust on my PCs.
```
─  rustc --version                                                                                                                     1 (0.186s)
rustc 1.69.0 (84c898d65 2023-04-16)

─  rustup --version                                                                                                                    
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.69.0 (84c898d65 2023-04-16)
```

I see that is productive release of pylyzer is 0.0.22 but mason pm and cargo show 0.0.20 version 
```
─  cargo search pylyzer                                                                                                                0 (0.154s)
pylyzer = "0.0.20"    # A static code analyzer & language server for Python
```
PIP show pylyzer 0.0.22

So, mason plugins install the same version 0.0.20 and els 1.23 nightly
With this version i have error from here
https://github.com/mtshiba/pylyzer/issues/19

So, wich steps i must do to make that pylyzer will work?
Thanks

**Comment by mtshiba** [comment]
The latest pylyzer 0.0.22 has been published to crates.io. The bug may be fixed in this release.

**Comment by amospalla** [comment]
It is starting for me today with version 0.0.23 on Lunarvim.

**Comment by kobzar** [comment]
The version of Neovim plugin and cargo was updated to 0.0.23
But still not positive results. 
Now i catch the same error but on enother place
```
[ERROR][2023-04-29 15:01:56] .../vim/lsp/rpc.lua:734	"rpc"	"pylyzer"	"stderr"	"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }', /home/kobzar/.cargo/registry/src/github.com-1ecc6299db9ec823/els-0.1.24-nightly.2/hir_visitor.rs:49:63\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by amospalla** [comment]
Try reinstalling pylyzer inside Lunarvim with:

`:MasonInstall pylyzer`

**Comment by kobzar** [comment]
![image](https://user-images.githubusercontent.com/1912842/235302711-3bba9e74-ff49-4b38-ae1e-c1f5d1696a85.png)
The same error

**Comment by mtshiba** [comment]
I think this was fixed in https://github.com/erg-lang/erg/commit/6c665157bcc0411dbbfb6c72b368ac74a2297e2c.

Please update to pylyzer 0.0.24.

**Comment by kobzar** [comment]
I was updated and finally its started and look like work. 
No errors, but crached when i try to open help on print fuction. For range - show without error. 
Also dont show error for dict range like
```
d = {1: "One"}
print(d[2])
```

So, the project is wery young. But i hope it will fixed in close future.
But my first problem is resolved. So topic is closed.
