### ISSUE TITLE
[Feature Request] Local package resolve

### ISSUE THREAD

**Issue by lkhphuc** [mtshiba/pylyzer#22]
Hi, thanks for all the great work. I'm looking forward to try this out soon.

One major feature preventing me to use it daily is the ability to resolve locally installed package in virtual environment.

I know this is already on the todo list in the readme but I just want to create a tracking issue to be notified when it is available. I hope that it is OK, but feel free to close it not.

**Comment by rtgiskard** [comment]
looking forward to the feature, switch back to pyright temporally

**Comment by nrydanov** [comment]
Hello, is there any updates on the feature? Can't wait to use pylyzer but, currently, it's the only problem I can't switch to it permamently.

And... probably I miss some of existing workarounds?

**Comment by simonlearnscoding** [comment]
can someone please update me to when module imports will work?

**Comment by nikaro** [comment]
@simonlearnscoding you can subscribe to issues (which is automatically done when you comment them) to be notified when they are solved.

**Comment by aiell0** [comment]
+1 would love to use pylyzer but this issue is preventing me from doing so right now.

**Comment by grihabor** [comment]
Pyright has [extraPaths](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) config entry to configure local modules. Pycharm has similar configuration option with [Source Roots](https://www.jetbrains.com/help/pycharm/content-root.html#root_types). 

Is there a config for pylyzer?

**Comment by ipkiss42** [comment]
Being able to configure pylyzer via a config file, to specify the venv path and the extra paths (similarly to what Pyright does), is also critical for my use case.

**Comment by clot27** [comment]
This is what stopping me to use pylyzer, back to pylsp till then.
