### ISSUE TITLE
Not yet implemented error when using with Neovim

### ISSUE THREAD

**Issue by desilinguist** [mtshiba/pylyzer#24]
Thank you for this project! I was so tired of `pyright` taking such a long time to analyze files in my large Python projects. 

However, when I try to use this with Neovim 0.9 on my Apple Silicon MacBook Pro, it quits with the following error:

```
[ERROR][2023-05-02 09:46:30] .../vim/lsp/rpc.lua:734	"rpc"	"pylyzer"	"stderr"	"thread 'main' panicked at 'not yet implemented', /Users/nmadnani/.cargo/registry/src/github.com-1ecc6299db9ec823/erg_compiler-0.6.12-nightly.4/context/eval.rs:1444:53\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

I installed `pylyzer` using Mason and configured it using lspconfig.

**Comment by mtshiba** [comment]
fixed in https://github.com/erg-lang/erg/commit/0603998bfcb940963d5ce108c4a5fe617e706e76.
