### ISSUE TITLE
Crash on help fuction

### ISSUE THREAD

**Issue by kobzar** [mtshiba/pylyzer#27]
pylyzer 0.0.25
This is very strange. For show documentation we are use ```Shift + K``` in vim/nvim
And this is work now when i try to use it for ```range()``` and some other operatos. 
But! If i try show help for ```print()``` fuction pylyzer is crashed

```
[ERROR][2023-05-04 10:56:19] .../vim/lsp/rpc.lua:734	"rpc"	"pylyzer"	"stderr"	"thread 'main' panicked at 'called 
`Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', 
/home/kobzar/.cargo/registry/src/github.com-1ecc6299db9ec823/els-0.1.24-nightly.6/hover.rs:183:77\n
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by mtshiba** [comment]
fixed in https://github.com/erg-lang/erg/commit/2fce9bda3bda251d71142ab80801aeac2623fcbe.
