### ISSUE TITLE
Installing pylyzer through Mason does not work (Neovim)

### ISSUE THREAD

**Issue by lsig** [mtshiba/pylyzer#29]
When I try to install pylyzer through Mason does not seem to work 

MasonLog: [ERROR Thu May 11 10:14:39 2023] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:200: Installation failed for Package(name=pylyzer) error=spawn: cargo failed with exit code 101 and signal 0. 

Neovim version: 0.9.0
Operating system: Ventura 13 (MacOS M1)

Maybe this is something on my end that I am doing wrong

![Screenshot 2023-05-11 at 10 35 10](https://github.com/mtshiba/pylyzer/assets/89947902/755fd52f-1dc6-42f5-b6f2-a4f7c9f20ec8)

**Comment by kobzar** [comment]
Move cursor to arrow and pres Enter. 
Go to end and show more full log. 
The same try to install pylyzer directly in terminal by cargo install pylyzer
and show full log

**Comment by lsig** [comment]
![Screenshot 2023-05-11 at 21 28 58](https://github.com/mtshiba/pylyzer/assets/89947902/3b16b3aa-6c1c-4dd3-bc6f-5a12546e7dbf)
![Screenshot 2023-05-11 at 21 32 54](https://github.com/mtshiba/pylyzer/assets/89947902/e43bff24-8cf1-455e-bcc8-f4e49370b7ec)
![Screenshot 2023-05-11 at 21 33 14](https://github.com/mtshiba/pylyzer/assets/89947902/70d48594-3e1a-4216-84f3-824d40e47e39)

**Comment by lsig** [comment]
Nevermind, I was running an older version of Cargo where unzip is an unstable method. Maybe add to the readme that latest version of Cargo is needed, thanks for the help.
