### ISSUE TITLE
Add with (... as ..., ... as ..., ...) syntax

### ISSUE THREAD

**Issue by jmwielandt** [mtshiba/pylyzer#30]
This is a valid syntax since ¿3.10? (not sure):

![imagen](https://github.com/mtshiba/pylyzer/assets/37153467/8fd754f7-68df-4e64-9df7-1edf5c198e76)

**Comment by mtshiba** [comment]
This is not a pylyzer problem, but a [rustpython_parser](https://github.com/RustPython/RustPython) problem.

**Comment by youknowone** [comment]
pylyzer is using very old copy of rustpython parser
