### ISSUE TITLE
inlay hint causes panic in neovim-nightly

### ISSUE THREAD

**Issue by quantum-booty** [mtshiba/pylyzer#38]
[ERROR][2023-05-28 19:49:18] .../vim/lsp/rpc.lua:734	"rpc"	"/home/henryw/.local/share/nvim/mason/bin/pylyzer"	"stderr"	"thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/henryw/.cargo/registry/src/github.com-1ecc6299db9ec823/els-0.1.26-nightly.0/inlay_hint.rs:213:36\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"

replicated with this neovim config:
https://github.com/mtshiba/pylyzer/issues/40

**Comment by mtshiba** [comment]
This problem has been resolved in v0.0.30, but the inlay hints feature is still unstable in pylyzer and it is recommended to turn it off.
