### ISSUE TITLE
Highlight issues

### ISSUE THREAD

**Issue by kobzar** [mtshiba/pylyzer#43]
pylyzer 0.3.1
neovim 9.1.1
MacOS/Linux

No errors/messages in LSP logs
pylyzer is runned. 
The help of function is mutch better now - thanks
But some fitches don't work again

![image](https://github.com/mtshiba/pylyzer/assets/1912842/935e3b48-4d31-4ba2-8766-ed6003405576)

On import ans function args the same colors (in jedy/pyright is different)
And next two line with out of range  - but pylyzer dont show errors.

From day to day pylyzer is better. In we are wait for first stable release that can work with it. Because its impossible at this time, but we are try to make fidback :)

**Comment by mtshiba** [comment]
I checked the code in Neovim/VSCode and had no problems. Try updating pylyzer to the latest version.

<img width="455" alt="スクリーンショット 2023-06-11 0 58 41" src="https://github.com/mtshiba/pylyzer/assets/45118249/702d84c2-2bc4-4fd4-9387-4d9edd5a4043">
