### ISSUE TITLE
Tags are not on the main branch 

### ISSUE THREAD

**Issue by Salamandar** [mtshiba/pylyzer#48]
Hello,
I'm currently packaging pylyzer on the Arch User Repository.
I'm discovering that the git tags aren't on the main branch, but on the crates.io branch.
So, I have a question : for the `pylyzer-git` package, that should track the dev branch, should it track the `main`or `crates.io` branch ?

Thanks for your reply !

**Comment by mtshiba** [comment]
Currently pylyzer uses two different RustPython parsers. The newer one is not published on crates.io (https://github.com/RustPython/Parser/issues/67) and I can't publish pylyzer either. So I created a `crates.io` branch with the older parser.

The main branch uses the latest parser. If you clone the repository and build pylyzer from source, you can select this branch.

**Comment by Salamandar** [comment]
Alright, thanks for the info ! I'll stay on the main branch then.
But would it be possible to add version tags on the main branch too then ? Thanks !

**Comment by mtshiba** [comment]
The creation of a tag triggers GitHub Actions that perform release work on the target branch. Therefore tags should be created on the `crates.io` branch.

**Comment by mtshiba** [comment]
`rustpython-parser` v0.3.0 is now available.

https://github.com/RustPython/Parser/pull/92

So I have released pylyzer v0.0.42.  I'll leave the `crates.io` branch undeleted for now, but note that the latest version has been moved to the main branch.
