### ISSUE TITLE
Error with pip installation

### ISSUE THREAD

**Issue by fbrodrigorezino** [mtshiba/pylyzer#58]
When installing using `pip install pylyzer`
when I try to run it, I get `[ERR] ERG_PATH not found`

**Comment by mtshiba** [comment]
If you have not installed Erg (pylyzer depends on it) and set ERG_PATH, you will get that error.
Even if that error is made, there should be no problem with the inspection.
If you want to erase the message, set ERG_PATH.

**Comment by johannesrave** [comment]
sorry to comment here, but i don't quite understand. 
if `pylyzer` depends on Erg, do i NEED to install Erg or is that optional? couldn't find that in the readme.

**Comment by mtshiba** [comment]
To be precise, pylyzer relies on Erg's type declaration library for the Python standard library. Without it, pylyzer cannot support imports from the Python standard library.
The easiest way to install this library is to install the Erg toolchain.
