### ISSUE TITLE
Add to langserver.org

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [mtshiba/pylyzer#63]
When you are ready, please add pylyzer to a list of language servers at langserver.org from the following repo.

https://github.com/langserver/langserver.github.io

**Comment by mtshiba** [comment]
Thanks for the suggestion!

pylyzer still has many features that are not fully available, so I will improve it more before submitting a PR.
Instead, I will submit a PR of the Erg Language Server, which is the LS backend of pylyzer.

**Comment by HIRANO-Satoshi** [comment]
That sounds great.
