### ISSUE TITLE
Question: Where to view errors and/or disable them?

### ISSUE THREAD

**Issue by aricursion** [mtshiba/pylyzer#79]
I'm trying out pylyzer for the first time and it's pretty great!

But, there are a couple features I'm a bit confused by. For example, functions with side effects are considered errors, which, while I generally understand might be undesirable, I'm a bit surprised that this is default. `print` for example feels like a common use case and not necessarily undesirable behavior. Or, for example,

```python
def test():
    x = 2
    d = {1: 2, 3: 4, 2: 5}
    y = d[x]
    return y


res = test()
print(res)
```
tells me that on the line assigning to `y` I cannot access a mutable object in a function. However, it's declared in the scope of the function so I don't see why this is a problem. Am I doing something wrong?

Please let me know!

**Comment by mtshiba** [comment]
This issue has been fixed in the latest version.
