### ISSUE TITLE
[ERR] ERG_PATH/lib/std.d not found 

### ISSUE THREAD

**Issue by tsoernes** [mtshiba/pylyzer#83]
Running pylyzer yields
```
[ERR] ERG_PATH/lib/std.d not found 
```

```
(base) torstein@x1extreme:~/Downloads/erg$ echo $ERG_PATH
/home/torstein/.erg
(base) torstein@x1extreme:~/Downloads/erg$ which erg
~/.erg/bin/erg
(base) torstein@x1extreme:~/Downloads/erg$ ls -l $ERG_PATH/lib
total 16
drwxr-xr-x. 1 root root  696 april 18 01:03 core
drwxr-xr-x. 1 root root  290 april 18 01:03 core.d
-rw-r--r--. 1 root root 9722 april 18 01:03 LICENCE
drwxr-xr-x. 1 root root 1924 april 18 01:03 pystd
-rw-r--r--. 1 root root  299 april 18 01:03 README.md
drwxr-xr-x. 1 root root  114 april 18 01:03 std
(base) torstein@x1extreme:~/Downloads/erg$ erg --version
Erg 0.6.34
```

**Comment by Orca-bit** [comment]
![image](https://github.com/mtshiba/pylyzer/assets/52285880/9643d290-e393-4fa7-bae7-eb6c0af7f18c)
I install erg by cargo, but it's only a binary file
I have no idea how to install these library
![image](https://github.com/mtshiba/pylyzer/assets/52285880/873e1364-eb31-4040-9d11-18f47d43d9bd)

**Comment by JulyFinal** [comment]
I find erg in my home `.erg`,  maybe u need run `export ERG_PATH="~/.erg"`

**Comment by mtshiba** [comment]
If for some reason the files under `lib` cannot be installed, you can reinstall them using the following method.

* pip reinstall

```sh
pip install --force-reinstall pylyzer
```
* cargo reinstall

```sh
cargo install --force pylyzer
```
* [ergup](https://github.com/mtshiba/ergup)

```sh
python3 <(curl -L https://github.com/mtshiba/ergup/raw/main/ergup.py)
```

**Comment by artkpv** [comment]
I have this issue on my Archlinux where I use pacman to install pylyzer (actually yay which is a wrapper over pacman) from https://aur.archlinux.org/packages/pylyzer-bin. 

It prints:

```
❯ pylyzer
[ERR] ERG_PATH/lib/core.d not found
```

My environment:
```
❯ LANG=en ls ${ERG_PATH}/lib
LICENCE  README.md  external  pystd  std  std.d

~
❯ pylyzer
[ERR] ERG_PATH/lib/core.d not found
```

**Comment by artkpv** [comment]
Continuing the last comment. I installed erg using AUR (Archlinux and pacman). And now there is no such error (core.d not found). But when I open a python file it fails with

> No entry file found in the current project

@mtshiba , do you know why it happens?

**Comment by Dronakurl** [comment]
It's the same here.

Here is to reproduce:
`cargo install pylyzer --locked`

Now run it on a single file

`pylyzer p.py`

```python
# p.py
import numpy as np


def wurst(xx: list[str]):
    print("wurst" + xx)
    print(np.array([1, 2, 3]))

wurst("hu")
```

Without the numpy part, `pylyzer` works and reports the type issues. In neovim, I can use "goto definition".
With the numpy part, it takes forever

Ubuntu 24.04
pylyzer 0.0.72
python 3.12

Maybe it's because I use `uv` and have the virtual environment in the same folder in `.venv` and it tries to analyze the whole numpy codebase. (Just a wild guess)
