### ISSUE TITLE
Is code signatures in the pipeline?

### ISSUE THREAD

**Issue by im-AMS** [mtshiba/pylyzer#89]
I used to use pyright, and was not happy with the sluggish performance.

Pylyzer is great in that sense, but I miss the code signatures feature from pyright. Will this ever be integrated in pylyzer?

**Comment by mtshiba** [comment]
The [signature help](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp) feature was originally implemented, but it was not worked properly due to a bug.
The bug has now been fixed in the latest version.
