### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by Salamandar** [mtshiba/pylyzer#9]
A non-issue too tell you guys thanks, and your software has been packaged on the AUR (Arch User Repository) :
stable release : https://aur.archlinux.org/packages/pylyzer
master build : https://aur.archlinux.org/packages/pylyzer-git

**Comment by mtshiba** [comment]
Oh, thanks for letting me know.

I may have to consider distributing binaries directly on GitHub releases, etc.

**Comment by Salamandar** [comment]
It's ok, for now the package itself builds the code, and it's not too long.
